[22기 이지훈] main page에서 category image만 넣기 
wecode-bootcamp-korea/22-1st-mangoPeace-backend pull request #11
Opened 2021-07-11 06:55 UTC by wlgns410

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-12 02:17 UTC, lordmyshepherd requested changes

2021-07-12 02:17 UTC, lordmyshepherd commented on restaurants/views.py
> +            return JsonResponse({"message":"success", "result":subcategory_list}, status=200)
**리뷰 1**
Main이 아니라 subcategory를 반환하는 엔드포인트 아닌가요?
엔드포인트도 `:8000/categories/<int:category_id>/mainlist`가 되면 URI만 보고 `mainlist`가 의미하는게 무엇인지 알 수 없습니다.
`RESTful`하게 엔드포인트를 구현하려면, 반드시 데이터 기준으로 `URI`를 만들어 주셔야 합니다.

**리뷰 2**
category_id를 인자로 넘겨 받았는데, 아래 코드에서는 사용하는 것 같지가 않네요?
카테고리에 해당하는 서브카테고리를 반환하는 엔드포인트 아닌가요?
```suggestion
class SubcategoryListView(View):
    def get(self, request, category_id):
        try:
            subcategorys = SubCategory.objects.all()           
            subcategory_list = []
            for subcategory in subcategorys:                 
                subcategory_list.append({
                    "image" : subcategory.restaurants.all()[0].foods.all()[0].images.all()[0].image_url                
                })

            return JsonResponse({"message":"success", "result":subcategory_list}, status=200)
```

2021-07-12 02:17 UTC, lordmyshepherd commented on restaurants/views.py
> +        except DataError:
마찬가지로 DataError는 무엇인가요?

2021-07-12 02:17 UTC, lordmyshepherd commented on restaurants/views.py
> +        except JSONDecodeError:
`JSONDecodeError`는 왜 필요한가요?

2021-07-12 10:21 UTC, wlgns410 commented on restaurants/views.py
> +        except DataError:
수정했습니다.

2021-07-12 10:21 UTC, wlgns410 commented on restaurants/views.py
> +        except JSONDecodeError:
수정했습니다.

2021-07-12 11:05 UTC, wlgns410 commented
![스크린샷 2021-07-12 오후 8 04 31](https://user-images.githubusercontent.com/81137234/125277491-72ebae80-e34c-11eb-8917-ba5128e18256.png)

2021-07-12 21:47 UTC, lordmyshepherd requested changes

2021-07-12 21:47 UTC, lordmyshepherd commented on restaurants/views.py
> +class MainListView(View):
Main <- 메인 페이지 기준으로 엔드포인트를 만드시면 안됩니다!

```suggestion
class SubCategoryListView(View):

```

2021-07-12 21:47 UTC, lordmyshepherd commented on restaurants/views.py
> +                    "image" : subcategory.restaurants.all()[0].foods.all()[0].images.all()[0].image_url
subcategory의 image를 상품에서 가져오는 건가요??
그리고 다른 정보들은 필요 없나요? (id, name 등..)

category테이블에 image_url을 추가하는게 코드가 깔끔해질 것 같습니다!

```suggestion
                    "image" : subcategory.restaurants.all()[0].foods.all()[0].images.all()[0].image_url                
```

2021-07-13 05:04 UTC, wlgns410 commented on restaurants/views.py
> +                    "image" : subcategory.restaurants.all()[0].foods.all()[0].images.all()[0].image_url
네. 이미지만 가져오려고 했습니다. DB에서 image_url에 144개가 있는데, 저희가 sub_category에 맞는 첫번째에만 사진을 넣어놔서 [0]으로 써서 가져왔는데요. 그럼 annotate로 category table에 image_url field를 만들라는 말씀이신가요? annotate라는 메서드는 많이 떨어져 있는 메서드라도 아무렇게나 사용가능한 건가요?

2021-07-14 04:23 UTC, wlgns410 commented
![스크린샷 2021-07-14 오후 1 23 18](https://user-images.githubusercontent.com/81137234/125560918-95c8b92b-9a6c-4bf3-a3bb-948e13ad4e4c.png)

2021-07-14 06:59 UTC, merged