메인 페이지 HIGH_LIST_VIEW
wecode-bootcamp-korea/22-1st-mangoPeace-backend pull request #14
Opened 2021-07-11 12:01 UTC by wlgns410

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
![스크린샷 2021-07-11 오후 8 54 20](https://user-images.githubusercontent.com/81137234/125194074-a403aa80-e28a-11eb-8a07-bedcc794b03d.png)

2021-07-12 02:38 UTC, lordmyshepherd requested changes

2021-07-12 02:38 UTC, lordmyshepherd commented on restaurants/urls.py
> +    path("/<int:restaurant_id>/high_ratings", HighListView.as_view())
최종적으로 해당 엔드포인트의 목적이 무엇인가요?
최신 레스토랑을 반환해주는게 목적인가요?

2021-07-12 02:38 UTC, lordmyshepherd commented on restaurants/views.py
> +    def get(self, request, restaurant_id):
restaurant_id는 어디서 사용되나요?

2021-07-12 02:38 UTC, lordmyshepherd commented on restaurants/views.py
> +            return JsonResponse({"message":"DATA_ERROR"}, status=400)
계속 보이네요.. 해당 에러는 언제 발생하는건가요?

2021-07-12 11:15 UTC, wlgns410 commented on restaurants/urls.py
> +    path("/<int:restaurant_id>/high_ratings", HighListView.as_view())
수정하겠습니다

2021-07-12 11:15 UTC, wlgns410 commented on restaurants/views.py
> +    def get(self, request, restaurant_id):
수정하겠습니다.

2021-07-13 07:53 UTC, wlgns410 commented on restaurants/views.py
> +            return JsonResponse({"message":"DATA_ERROR"}, status=400)
수정했습니다.

2021-07-13 07:53 UTC, wlgns410 commented
<img width="892" alt="스크린샷 2021-07-13 오후 4 52 50" src="https://user-images.githubusercontent.com/81137234/125413461-fcf74ace-663b-4bb6-af08-239c4b835f85.png">

2021-07-13 09:15 UTC, lordmyshepherd requested changes

2021-07-13 09:15 UTC, lordmyshepherd commented on restaurants/views.py
> +
레스토랑중에 별점순으로 목록을 가져오는 필터링 기능입니다.
아래와 같이 filtering 기능은 quey paramter를 사용해서 만들어 주세요!
`:8000/restaurants?ordering=average_rating`


```suggestion
class RestaurantsView(View):
    def get(self, request):
        try:
            ordering = request.GET.get("orderting") .
                            
            restaurants = Restaurant.objects.annotate(average_rating=Avg("review__rating")).order_by("-average_rating")
            
            restaurant_list = []
            
            for restaurant in restaurants: 
                restaurant_list.append({
                    "sub_category"      : restaurant.sub_category.name,
                    "category"          : restaurant.sub_category.category.name,
                    "restaurant_name"   : restaurant.name,
                    "address"           : restaurant.address,
                    "rating"            : round(restaurant.average_rating, 1),
                    "image"             : restaurant.foods.all()[0].images.all()[0].image_url,
                    "restaurant_id"     : restaurant.id
                })

            return JsonResponse({"message":"success", "result":restaurant_list[:5]}, status=200)

        except Restaurant.DoesNotExist:
            return JsonResponse({"message":"RESTAURANT_NOT_EXIST"}, status=404)

```

2021-07-13 11:38 UTC, wlgns410 commented
![스크린샷 2021-07-13 오후 8 35 36](https://user-images.githubusercontent.com/81137234/125445450-99acb13a-08be-4dfb-92a6-2dc4aa071bb2.png)

2021-07-13 11:39 UTC, wlgns410 commented on restaurants/views.py
> +
넵 완료했습니다. ordering이 아닌 filtering으로 한 이유는 둘의 주소가 겹칠 것 같아서 filtering으로 명명했습니다.

2021-07-13 12:27 UTC, lordmyshepherd commented
👍  LGTM 정말 고생 많으셨습니다!!

2021-07-13 12:27 UTC, merged