레스토랑 상세 VIEW
wecode-bootcamp-korea/22-1st-mangoPeace-backend pull request #16
Opened 2021-07-11 14:41 UTC by wonseok2877

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-12 03:44 UTC, lordmyshepherd requested changes

2021-07-12 03:44 UTC, lordmyshepherd commented on restaurants/views.py
> +            is_wished           = fake_user_instance.wishlist_restaurants.filter(id=restaurant_id).exists()
`fake_user_instance`는 뭔가요?
```suggestion
            is_wished           = fake_user_instance.wishlist_restaurants.filter(id=restaurant_id).exists()
```

2021-07-12 03:44 UTC, lordmyshepherd commented on restaurants/views.py
> +            reviews_queryset    = Restaurant.objects.get(id=restaurant_id).review_set.all()
`line 10` 에서 `restaurant = Restaurant.objects.get(id=restaurant_id)` 이미 호출하고 있기 때문에 불필요하게 아래에서 한번 더 선언하는 이유가 궁굼합니다

2021-07-12 03:44 UTC, lordmyshepherd commented on restaurants/views.py
> +            review_count        = Restaurant.objects.get(id=restaurant_id).review_set.all().count()
여기도 마찬가지입니다!

2021-07-12 03:44 UTC, lordmyshepherd commented on restaurants/views.py
> +        }
align 맞춰주세요!
```suggestion
            result = {
            "id"           : restaurant_instance.id,
            "sub_category" : restaurant_instance.sub_category.name,
            "name"         : restaurant_instance.name,
            ...
        }
```

2021-07-12 11:50 UTC, wonseok2877 commented on restaurants/views.py
> +            is_wished           = fake_user_instance.wishlist_restaurants.filter(id=restaurant_id).exists()
아직 decorator (token과 일치하는지 확인하는 로직)을 merge하지 않은 상태여서 저렇게 했었습니다! 
이 branch에서는 에러가 나더라도 decorator을 호출하면 될까요?

2021-07-12 12:15 UTC, wonseok2877 commented on restaurants/views.py
> +            is_wished           = fake_user_instance.wishlist_restaurants.filter(id=restaurant_id).exists()
merge됐을 때 생각해서 토큰 받는 decorator 호출하는 쪽으로 했습니다!

2021-07-12 12:16 UTC, wonseok2877 commented on restaurants/views.py
> +            reviews_queryset    = Restaurant.objects.get(id=restaurant_id).review_set.all()
저도 궁금합니다...ㅋㅋㅋ 고쳤습니다!

2021-07-12 12:16 UTC, wonseok2877 commented on restaurants/views.py
> +            review_count        = Restaurant.objects.get(id=restaurant_id).review_set.all().count()
옙!

2021-07-12 12:16 UTC, wonseok2877 commented on restaurants/views.py
> +            reviews_queryset    = Restaurant.objects.get(id=restaurant_id).review_set.all()
추가로 끝에 `_instance`로 반복되는 변수명 스타일은 바꿨습니다!

2021-07-12 12:18 UTC, wonseok2877 commented on restaurants/views.py
> +        }
고쳤습니다!

2021-07-12 21:49 UTC, lordmyshepherd commented on restaurants/views.py
> +            is_wished           = fake_user_instance.wishlist_restaurants.filter(id=restaurant_id).exists()
이런 경우는 decorator코드가 merge되고 나서 올리는게 맞습니다!
main branch에 merge 되는 코드는 제대로 동작하는 코드여야 합니다~

decorator PR 머지되었으니 마지막 테스트 해보시고 코멘트 남겨주세요~~

2021-07-12 21:50 UTC, lordmyshepherd commented on restaurants/views.py
> +            reviews_queryset    = Restaurant.objects.get(id=restaurant_id).review_set.all()
피드백 반영 잘 해주시고, github 소통도 너무 잘해주셔서 감사합니다!👍👍

2021-07-12 22:14 UTC, lordmyshepherd requested changes

2021-07-12 22:14 UTC, lordmyshepherd commented on restaurants/views.py
> +            "average_rating" : average_rating,
dictionary 내부에 indentation만 맞춰주시면 좋을 것 같습니다!
```suggestion
                "id"             : restaurant.id,
                "sub_category"   : restaurant.sub_category.name,
            "name"           : restaurant.name,
            "address"        : restaurant.address,
            "phone_number"   : restaurant.phone_number,
            "coordinate"     : restaurant.coordinate,
            "open_time"      : restaurant.open_time,
            "updated_at"     : restaurant.updated_at,
            "is_wished"      : is_wished,
            "review_count"   : review_count,
            "average_rating" : average_rating,
```

2021-07-12 22:14 UTC, lordmyshepherd commented on restaurants/views.py
> +            }
filter를 매번 새롭게 걸어서 count를 하면 데이터베이스를 여러번 hit 할 것 같습니다.
Django에서 `Subquery`를 활용해서 구현해 볼 수도 있을 것 같습니다!

**공식문서**
<img width="515" alt="스크린샷 2021-07-13 오전 7 09 03" src="https://user-images.githubusercontent.com/53214510/125362056-369a6b80-e3a9-11eb-8b7e-73fe9fa6c77b.png">

`SubqueryAggregate` class 모듈도 있네요 ㅎㅎ <- 라이브러리로 쉽게 구현할 수 있으니 위에 방법을 시도해보면 좋겠네요!
https://github.com/martsberger/django-sql-utils

2021-07-13 03:00 UTC, wonseok2877 commented
subquery는 다음생에 하겠습니다..감사합니다!!

2021-07-13 03:00 UTC, wonseok2877 commented
subquery제외하고 리뷰사항 반영했습니다!

2021-07-13 06:49 UTC, lordmyshepherd approved these changes

2021-07-13 06:49 UTC, lordmyshepherd commented on restaurants/views.py
> +            }
```python
     SELECT 
         id,
         name,
         (SELECT COUNT(*) FROM reviews JOIN restaurants ON restaurant.id = review.rastaurant_id WHERE review.rating=1) AS rating_one,
         (SELECT COUNT(*) FROM reviews JOIN restaurants ON restaurant.id = review.rastaurant_id WHERE review.rating=2) AS rating_tow,
         (SELECT COUNT(*) FROM reviews JOIN restaurants ON restaurant.id = review.rastaurant_id WHERE review.rating=3) AS rating_three,
         ..
       FROM restaurants r
       WHERE r.id = 1


```

2021-07-13 06:50 UTC, lordmyshepherd commented
LGTM 👍

2021-07-13 06:50 UTC, merged