레스토랑 음식 정보 VIEW
wecode-bootcamp-korea/22-1st-mangoPeace-backend pull request #17
Opened 2021-07-11 14:53 UTC by wonseok2877

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-13 06:59 UTC, lordmyshepherd requested changes

2021-07-13 06:59 UTC, lordmyshepherd commented on restaurants/urls.py
> +    path("/<int:restaurant_id>/food", RestaurantFoodView.as_view()),
```suggestion
    path("/<int:restaurant_id>/foods", RestaurantFoodListView.as_view()),
```

2021-07-13 06:59 UTC, lordmyshepherd commented on restaurants/views.py
> +class RestaurantFoodView(View):
```suggestion

```

2021-07-13 06:59 UTC, lordmyshepherd commented on restaurants/views.py
> +            average_price = foods.aggregate(Avg("price"))["price__avg"]
`Restaurant` 엔드포인트로 이동!

2021-07-13 06:59 UTC, lordmyshepherd commented on restaurants/views.py
> +                foods_list.append(food)
이참에 한번 `list compherension`도 사용해보시면 좋을 것 같아요~

2021-07-13 08:23 UTC, wonseok2877 commented
모두 수정했습니다!
conflict들은 github쪽에서 고쳐도 괜찮을까요?

2021-07-13 09:15 UTC, lordmyshepherd commented
컨플릭트는 터미널 상에서 고쳐주세요!

2021-07-13 11:12 UTC, wonseok2877 commented
수정했습니다!

2021-07-13 12:27 UTC, lordmyshepherd commented
컨플릭트 해결해주세요!

2021-07-13 14:02 UTC, wonseok2877 commented
죄송합니다ㅠㅜ 그동안 main branch에 변화가 있는지 몰랐습니다
감사합니다!

2021-07-14 01:31 UTC, lordmyshepherd requested changes

2021-07-14 01:31 UTC, lordmyshepherd commented on restaurants/views.py
> +            foods_list = [{"id":f.id, "name":f.name, "price":f.price, "images":[i.image_url for i in f.images.all()]} for f in foods]
변수를 줄여서 사용하는 방법은 코드의 가독성을 안좋게 만들기 때문에, 반드시 다른 사람이 코드를 읽어도 변수를 제대로 이해할 수 있도록 작성해 주세요~

```suggestion
            foods_list = [{
                "id"     : f.id, 
                "name"   : f.name, 
                "price"  : f.price, 
                "images" : [image.image_url for image in food.images.all()]
            } for food in foods]
```

2021-07-14 05:40 UTC, wonseok2877 commented
변수명 수정 완료했습니다!

2021-07-14 07:02 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-07-14 07:04 UTC, merged