레스토랑 상세 리뷰 VIEW
wecode-bootcamp-korea/22-1st-mangoPeace-backend pull request #19
Opened 2021-07-11 15:22 UTC by wonseok2877

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-13 07:10 UTC, lordmyshepherd requested changes

2021-07-13 07:10 UTC, lordmyshepherd commented on restaurants/views.py
> +            UNIT_PER_PAGE = 10
`limit` `offset`을 사용하지 않는 이유가 있나요?

2021-07-13 07:10 UTC, lordmyshepherd commented on restaurants/views.py
> +            limit         = int(request.GET.get("limit", 1)) * UNIT_PER_PAGE
-> 'offset' 'limit'으로 구현해 주세요~

2021-07-13 07:10 UTC, lordmyshepherd commented on restaurants/views.py
> +
마찬가지로 Review에서 시작해서 가져오면 가독성이 더 좋아질 것 같습니다~

2021-07-13 07:10 UTC, lordmyshepherd commented on restaurants/views.py
> +                review_list.append(review)
'list comprehension'

2021-07-13 07:10 UTC, lordmyshepherd commented on restaurants/views.py
> +                        "profile_image":r.user.profile_url if hasattr(r.user, "profile_url") else None,
`Null=True` 옵션 확인해주시면 좋을 것 같아요.

2021-07-13 11:21 UTC, wonseok2877 commented on restaurants/views.py
> +            UNIT_PER_PAGE = 10
해당 사항 수정했습니다!

2021-07-13 11:22 UTC, wonseok2877 commented on restaurants/views.py
> +            limit         = int(request.GET.get("limit", 1)) * UNIT_PER_PAGE
해당 사항 수정했습니다!

2021-07-13 11:25 UTC, wonseok2877 commented on restaurants/views.py
> +
해당 사항 수정했습니다!

2021-07-13 11:25 UTC, wonseok2877 commented on restaurants/views.py
> +                review_list.append(review)
해당 사항 수정했습니다!

2021-07-13 11:27 UTC, wonseok2877 commented on restaurants/views.py
> +                        "profile_image":r.user.profile_url if hasattr(r.user, "profile_url") else None,
해당 사항 수정했습니다!

2021-07-13 14:05 UTC, wonslee commented
main branch와 conflice 없도록 수정했습니다!

2021-07-14 01:34 UTC, lordmyshepherd requested changes

2021-07-14 01:34 UTC, lordmyshepherd commented on restaurants/views.py
> +        limit         = int(request.GET.get("limit", 10))
👍

2021-07-14 01:34 UTC, lordmyshepherd commented on restaurants/views.py
> +            } for r in reviews]
Align 맞춰주시고, r -> review로 바꿔주세요.

```suggestion
        review_list   = [{
            "user":{
                "id":r.user.id,
                "nickname":r.user.nickname,
                "profile_image":r.user.profile_url,
                "review_count":r.user.reviewed_restaurants.count()
                },
                "id":r.id,
                "content" : r.content,
                "rating":r.rating,
                "created_at":r.created_at,
            } for r in reviews]
```

2021-07-14 04:45 UTC, wonseok2877 commented on restaurants/views.py
> +            } for r in reviews]
해당 사항 수정했습니다!

2021-07-14 07:10 UTC, wonseok2877 commented on restaurants/views.py
> +            } for r in reviews]
dictionary convention 해결했습니다!

2021-07-14 07:28 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-07-14 07:28 UTC, merged