상세 페이지 Top-List VIEW
wecode-bootcamp-korea/22-1st-mangoPeace-backend pull request #21
Opened 2021-07-13 11:09 UTC by wlgns410

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x
<img width="818" alt="스크린샷 2021-07-13 오후 8 06 54" src="https://user-images.githubusercontent.com/81137234/125441757-d2ba98ae-db90-4f98-97b1-c292b8d752a7.png">
] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-13 11:19 UTC, wlgns410 commented
상세 페이지 Restaurant-Rating-List VIEW 브랜치가 엉켜서 새로 만든 브랜치입니다. 쿼리 파라미터, annotate 사용하였습니다.

2021-07-14 01:59 UTC, lordmyshepherd requested changes

2021-07-14 01:59 UTC, lordmyshepherd commented on restaurants/views.py
> +class TopListView(View):
RESTful 하게 엔드포인트를 구현하기 위해서, 기존에 작업 하셨던 `PopularRestaurantView`와 합쳐주세요!

자세하게 설명 드리면, restaturant 리스트를 반환하는 엔드포인트를 하나로 만들어주세요. 하나의 엔드포인트에서 input으로 들어오는 filtering 조건에 맞는 값을 반환하도록 아래와 같이 수정해주세요!

`/resatarunts?filtering=-avg..`
`/resatarunts?filtering=-ordering`

```python
class RestarantListView(View):
    def get(self, request):
        ...

```

2021-07-14 02:00 UTC, lordmyshepherd commented
컨플릭트도 해결해주세요~

2021-07-14 05:32 UTC, wlgns410 commented
![스크린샷 2021-07-14 오후 2 32 08](https://user-images.githubusercontent.com/81137234/125568181-a32cb3d5-dd80-4139-bcdf-71afc1805b69.png)

2021-07-14 05:32 UTC, wlgns410 commented on restaurants/views.py
> +class TopListView(View):
수정완료했습니다!

2021-07-14 12:43 UTC, wlgns410 commented
![스크린샷 2021-07-14 오후 9 42 18](https://user-images.githubusercontent.com/81137234/125623848-1e700feb-c785-4918-84de-887586195bf5.png)
![스크린샷 2021-07-14 오후 9 42 28](https://user-images.githubusercontent.com/81137234/125623856-1c6e5315-8a12-4d23-9b44-d920e79d9243.png)

2021-07-15 02:38 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-07-15 02:38 UTC, lordmyshepherd commented
프로젝트가 끝나고 위에 피드백 드린대로 리펙토링 해주세요!!

2021-07-15 02:38 UTC, merged