Feature/filtering
wecode-bootcamp-korea/22-1st-mangoPeace-backend pull request #25
Opened 2021-07-13 14:57 UTC by showmethr23

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 다중 필터링 기능
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-13 15:00 UTC, showmethr23 commented
<img width="1295" alt="스크린샷 2021-07-13 오후 9 57 59" src="https://user-images.githubusercontent.com/62336688/125475187-a18133c2-6e8c-4b63-8c9e-8b18eaf5a5a7.png">
<img width="1292" alt="스크린샷 2021-07-13 오후 9 58 07" src="https://user-images.githubusercontent.com/62336688/125475203-09239a59-8f87-4711-a6d6-72646c8bb577.png">
<img width="1299" alt="스크린샷 2021-07-13 오후 9 58 14" src="https://user-images.githubusercontent.com/62336688/125475208-ed3781ab-8eb3-4029-b458-ecc3c59feb39.png">

프로젝트 URI 수정하겠습니다..

2021-07-14 02:38 UTC, lordmyshepherd requested changes

2021-07-14 02:38 UTC, lordmyshepherd commented on filters/views.py
> +class FilteringVeiw(View):
filter 기능은 view가 별도로 존재하는게 아니라, 각각의 자원(여기서는, category 정보, restaurant 정보,..)을 호출하는 엔드포인트에 적용되는 기능입니다,

그렇기 때문에. filter app을 생성하지 않고, 기존 category, restaurant app에서 구현해주셔야 합니다.
그렇게되면 URI는 아래와 같이 되겠죠?

`/categories?keyword=..`
`/sub_categories?keyword=..`
`/resaturants?keyword=..`

**결론적으로는** FilteringView는 `CategoriesView`, `SubCategoiresView`, ...로 분리해서 구현해주시고, 요청하는 측(frontend)에서 3가지 정보가 모두 필요한 경우에는 fetch(backend api 호출하는 javascript 함수)를 3번 요청하는 방향이 옳바른 방향입니다.

다만, 이미 프론트엔드와 작업이 많이 진행된 상태여서 프론트에서 바꾸기 어렵다고하면 코멘트 남겨주세요!

2021-07-14 02:38 UTC, lordmyshepherd commented on searches/views.py
> +            # result = [{
불필요한 코드는 지워주세요!

2021-07-14 10:22 UTC, showmethr23 commented on searches/views.py
> +            # result = [{
수정하였습니다!

2021-07-14 10:23 UTC, showmethr23 commented on filters/views.py
> +class FilteringVeiw(View):
일단은 프론트랑 얘기해봤을때 현재는 어려워서 프로젝트 끝나고 리팩토링 해보겠습니다!

2021-07-15 02:39 UTC, lordmyshepherd requested changes

2021-07-15 02:39 UTC, lordmyshepherd commented on searches/views.py
> +            # result = [{
아직 주석이 남아있네요 지워주세요!

2021-07-15 02:39 UTC, lordmyshepherd commented
컨플릭트 해결해주세요~

2021-07-15 04:44 UTC, showmethr23 commented on searches/views.py
> +            # result = [{
해결 한것 같습니다

2021-07-15 08:19 UTC, lordmyshepherd commented
:LGTM 👍

2021-07-15 08:20 UTC, merged