[싸우지망고 백엔드] 회원가입 view
wecode-bootcamp-korea/22-1st-mangoPeace-backend pull request #3
Opened 2021-07-08 07:03 UTC by wonseok2877

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-08 07:27 UTC, wonseok2877 commented
![Screenshot from 2021-07-08 16-22-13](https://user-images.githubusercontent.com/72124326/124880588-6b08d300-e009-11eb-8ba8-316f2b62c62d.png)

2021-07-08 10:50 UTC, lordmyshepherd requested changes

2021-07-08 10:50 UTC, lordmyshepherd commented on users/views.py
> +                raise ValidationError(message=None)
검증하는 함수가 많은 경우에 module로 빼셨네요!! 👍
여기서 한 단계 더 나아가서, 해당 검증 로직은 User 회원가입시에만 필요한 로직이므로 아예 Class로 관리하는게 어떨까요?

```python

REGEX_PHONE_NUMBER = '.....'

Class User(models.Model):
	..
	
	@classmethod
	def is_validated(cls, user):
		if not re.match(REGEX_PHONE_NUMBER, user["phone_number"]):
			return False
		..
		
		return True

```

```python

	is_validated = User.is_validated(user)

	if not is_validated:
		return ..

	...

```

2021-07-08 11:01 UTC, lordmyshepherd requested changes

2021-07-08 11:01 UTC, lordmyshepherd commented on users/views.py
> +        except Exception:
`JSONDecodeError`, `KeyError`와 같이 예측할 수 있는 error를 핸들링 해주는 것은 잘 하셨습니다.
내가 예측하지 못하는 에러를 `Exception` Class를 사용해서 구현하는 방법은 나중에 개발자로 하여금 디버깅을 어렵게 만들기 때문에, 해당 에러처리는 지양해주세요~

2021-07-08 14:25 UTC, wonseok2877 commented on users/views.py
> +                raise ValidationError(message=None)
넵 감사합니다!! 공부해보겠습니다!

2021-07-08 14:25 UTC, wonseok2877 commented on users/views.py
> +        except Exception:
넵 알겠습니다!

2021-07-09 04:47 UTC, wonseok2877 commented on users/views.py
> +                raise ValidationError(message=None)
해당 사항은 model브랜치에서 수정 완료했습니다!

2021-07-10 13:56 UTC, closed without merging