[싸우지망고 백엔드] 로그인 view
wecode-bootcamp-korea/22-1st-mangoPeace-backend pull request #8
Opened 2021-07-10 14:38 UTC by wonseok2877

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-07-12 02:11 UTC, lordmyshepherd requested changes

2021-07-12 02:11 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse({"message":"USER_NOT_EXIST"}, status=400)
존재하지 않는 경우, 404를 반환해주세요~

2021-07-12 02:11 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse({"message": "DATA_ERROR"}, status=400)
DataError는 어떤 케이스인가요?

2021-07-12 04:36 UTC, wonseok2877 commented on users/views.py
> +            return JsonResponse({"message": "DATA_ERROR"}, status=400)
특정 테이블의 column 요구사항 (예: max_length)에 반하는 데이터가 들어왔을 때 생기는 에러입니다! regex validation으로 한번 검증하기는 하지만 혹시나 놓친 부분이 있을까 해서 넣었었습니다. 
우선은 뺐습니다!

2021-07-12 04:42 UTC, wonseok2877 commented on users/views.py
> +            return JsonResponse({"message":"USER_NOT_EXIST"}, status=400)
알겠습니다! 404로 바꿨습니다!

2021-07-12 21:36 UTC, lordmyshepherd commented on users/views.py
> +            return JsonResponse({"message": "DATA_ERROR"}, status=400)
잘 알고 사용하고 계시군요!! 👍👍 추가해주세요~
제가 리뷰 남겼다고해서 무조건 수정하실 필요가 없습니다! 원석님께서 생각하신대로 논리적으로 사용하신 목적을 가지고 소통하시면서 최종 내용만 반영해주시면되요~

2021-07-13 01:45 UTC, wonseok2877 commented on users/views.py
> +            return JsonResponse({"message": "DATA_ERROR"}, status=400)
넵! 다시 추가했습니다ㅎ

2021-07-13 06:33 UTC, lordmyshepherd approved these changes
LGTM 👍

2021-07-13 06:34 UTC, merged